baseURL = 'https://www.gavanlamb.com'
languageCode = 'en-us'
title = 'Gavan Lamb'
relativeURLs = true

[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

# Mount the local ./assets folder so Hugo includes all its contents
[[module.mounts]]
source = "assets"
target = "static"
