name: Create release

on:
#  push:
#    branches:
#      - develop
#    paths-ignore:
#      - version.json
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  cancel-in-progress: false
  group: create-release-${{ github.head_ref }}

jobs:
  create_release_branch:
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: gavanlamb/github-actions/.github/actions/version/create-release@main
        name: Create release
        id: create-release
