name: Create Release

on:
#  push:
#    branches:
#      - develop
#    paths-ignore:
#      - version.json
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create release from'
        required: true
        default: 'develop'

permissions:
  contents: write
  pull-requests: write

jobs:
  create_release_branch:
    name: Create release branch
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}-build
    steps:
      - uses: actions/checkout@v4
        name: Fetch repo
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          fetch-tags: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - name: Install NBGV
        shell: bash
        run: dotnet tool update -g nbgv --version 3.6.133
      - name: Setup git user
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Prepare Release
        id: prepare-release
        shell: bash
        run: |
          version=$(nbgv prepare-release --format json | jq -c .)
          echo $version
          current_branch=$(jq -r '.CurrentBranch.Name' <<< "$version")
          echo "current-branch=$current_branch" >> $GITHUB_OUTPUT
          new_branch=$(jq -r '.NewBranch.Name' <<< "$version")
          echo "new-branch=$new_branch" >> $GITHUB_OUTPUT
      - name: Push ${{ steps.prepare-release.outputs.current-branch }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.prepare-release.outputs.current-branch }}
          tags: true
      - name: Push ${{ steps.prepare-release.outputs.new-branch }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.prepare-release.outputs.new-branch }}
          tags: true
          force: true
