name: Preview

on:
  pull_request:
    branches-ignore:
      - main

env:
  artifactName: Website

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}-deploy
    steps:
      - uses: actions/checkout@v4
        name: Fetch repo
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          fetch-tags: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - name: Generate version
        uses: gavanlamb/github-actions/.github/actions/generate-version@main
        id: version
      - name: Build site
        uses: gavanlamb/github-actions/.github/actions/build-hugo-for-github-pages@main
        with:
          artifactName: ${{ env.artifactName }}
          commitBy: ${{ github.actor }}
          commitDate: ${{ steps.version.outputs.GitCommitDate }}
          commitId: ${{ steps.version.outputs.GitCommitId }}
          destinationDirectory: site
          sourceDirectory: docs
          semver: ${{ steps.version.outputs.SemVer2 }}
          version: ${{ steps.version.outputs.Version }}
  Preview:
    name: Preview
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}-deploy
    environment: Preview
    steps:
      - name: Deploy ${{ env.artifactName }}
        uses: gavanlamb/github-actions/.github/actions/deploy-artifact-to-s3@main
        with:
          artifactName: ${{ env.artifactName }}
          artifactDirectory: site
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsS3Bucket: ${{ vars.AWS_S3_CICD_BUCKET }}
          awsS3Path: ${{ github.repository }}/${{ github.ref }}/site
          awsS3Region: ${{ vars.AWS_DEFAULT_REGION }}
