name: Preview

on:
  pull_request:
    branches-ignore:
      - main

env:
  artifactName: Website

concurrency:
  cancel-in-progress: false
  group: preview-${{ github.head_ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - name: Generate version
        uses: gavanlamb/github-actions/.github/actions/version/generate@main
        id: version
      - name: Build site
        uses: gavanlamb/github-actions/.github/actions/hugo/build@main
        with:
          artifactName: ${{ env.artifactName }}
          commitBy: ${{ github.actor }}
          commitDate: ${{ steps.version.outputs.GitCommitDate }}
          commitId: ${{ steps.version.outputs.GitCommitId }}
          destinationDirectory: site
          sourceDirectory: docs
          semanticVersion: ${{ steps.version.outputs.SemVer2 }}
          version: ${{ steps.version.outputs.Version }}
  Preview:
    name: Preview
    runs-on: ubuntu-latest
    needs: build
    environment: Preview
    steps:
      - name: Deploy ${{ env.artifactName }}
        uses: gavanlamb/github-actions/.github/actions/hugo/deploy-to-s3@main
        with:
          artifactName: ${{ env.artifactName }}
          artifactDirectory: site
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsS3Bucket: ${{ vars.AWS_S3_CICD_BUCKET }}
          awsS3Path: ${{ github.repository }}/${{ github.head_ref }}/site
          awsS3Region: ${{ vars.AWS_DEFAULT_REGION }}
