name: Preview

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  artifactName: Website

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref_name }}-deploy
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v4
        name: Fetch repo
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          fetch-tags: true
      - name: Generate version
        uses: gavanlamb/github-actions/.github/actions/generate-version@main
        id: version
      - name: Build site
        uses: gavanlamb/github-actions/.github/actions/build-hugo-for-github-pages@main
        with:
          artifactName: ${{ env.artifactName }}
          destinationDirectory: site
          sourceDirectory: docs
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref_name }}-deploy
    environment: Preview
    steps:
      - name: Deploy ${{ env.artifactName }}
        uses: gavanlamb/github-actions/.github/actions/deploy-artifact-to-s3@main
        with:
          artifactName: ${{ env.artifactName }}
          artifactDirectory: site
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsS3Bucket: ${{ vars.AWS_S3_CICD_BUCKET }}
          awsS3Path: ${{ github.repository }}/${{ github.ref_name }}/site
          awsS3Region: ${{ vars.AWS_DEFAULT_REGION }}
