name: 'Preview'

on:
  pull_request:

env:
  artifact-name: Website

concurrency:
  cancel-in-progress: false
  group: preview-${{ github.ref_name }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
      - name: Get version
        id: get-version
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          targetPath: ./
          disableCache: true
          useConfigFile: true
          configFilePath: GitVersion.yml
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - name: Build site
        id: build
        uses: gavanlamb/github-actions/.github/actions/hugo/build@main
        with:
          commit-by: ${{ github.actor }}
          commit-date: ${{ steps.get-version.outputs.commitDate }}
          commit-id: ${{ steps.get-version.outputs.sha }}
          destination-directory: site
          source-directory: docs
          version: ${{ steps.get-version.outputs.semVer }}
      - name: Archive site
        uses: gavanlamb/github-actions/.github/actions/archive@main
        with:
          artifact-name: ${{ env.artifact-name }}
          destination-directory: docs
          source-directory: ${{ steps.build.outputs.destination-directory }}

  preview:
    name: Preview
    runs-on: ubuntu-latest
    needs: build
    env:
      site-path: ${{ github.repository }}/release/preview${{ github.event.pull_request.number }}/site
    environment: 
      url: https://gavanlamb-github-actions-assets.s3.ap-southeast-2.amazonaws.com/${{ env.site-path }}/index.html
      name: Preview${{ github.event.pull_request.number }}
    steps:
      - name: Deploy ${{ env.artifact-name }}
        uses: gavanlamb/github-actions/.github/actions/hugo/deploy-to-s3@main
        with:
          artifact-name: ${{ env.artifact-name }}
          artifact-directory: site
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-s3-bucket: ${{ vars.AWS_S3_CICD_BUCKET }}
          aws-s3-path: ${{ env.site-path }}
          aws-s3-region: ${{ vars.AWS_DEFAULT_REGION }}
