name: Prepare pull request for review

on:
  pull_request:
    types:
      - opened
      - reopened

concurrency:
  cancel-in-progress: false
  group: pull-request-opened-${{ github.ref_name }}

jobs:
  update-pr-description:
    name: Update PR Description
    runs-on: ubuntu-latest
    steps:
      - name: Get issue details
        uses: gavanlamb/github-actions/.github/actions/jira/get-issue-details@main
        id: get-issue-details
        with:
          baseUrl: https://gavanlamb-team-1vid7fblvall.atlassian.net
          userEmail: mail@gavanlamb.com
          apiToken: ${{ secrets.JIRA_API_TOKEN }}
      - name: Update issue details
        uses: gavanlamb/github-actions/.github/actions/jira/change-issue-status@main
        if: ${{ steps.get-issue-details.outputs.type == 'subtask' }}
        with:
          baseUrl: https://gavanlamb-team-1vid7fblvall.atlassian.net
          userEmail: mail@gavanlamb.com
          apiToken: ${{ secrets.JIRA_API_TOKEN }}
          identifier: ${{ steps.get-issue-details.outputs.identifier }}
          status: Review
      - name: Update PR
        uses: gavanlamb/github-actions/.github/actions/pull-request/update-pr@main
        id: update-pr
        with:
          issueIdentifier: ${{ steps.get-issue-details.outputs.identifier }}
          issueTitle: ${{ steps.get-issue-details.outputs.title }}
          issueUrl: ${{ steps.get-issue-details.outputs.url }}
          environment: preview${{ github.event.pull_request.number }}
      - name: Send message
        uses: gavanlamb/github-actions/.github/actions/slack/pull-request-created@main
        if: always()
        with:
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          title: ${{ steps.update-pr.outputs.title }}
