name: 'Pull request: build and deploy'

on:
  pull_request:
    branches-ignore:
      - main

env:
  artifactName: Website

concurrency:
  cancel-in-progress: false
  group: pull-request-${{ github.ref_name }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ steps.version.outputs.Version }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Generate version
        uses: gavanlamb/github-actions/.github/actions/version/generate@main
        id: version
      - name: Build site
        uses: gavanlamb/github-actions/.github/actions/hugo/build@main
        with:
          artifactName: ${{ env.artifactName }}
          commitBy: ${{ github.actor }}
          commitDate: ${{ steps.version.outputs.GitCommitDate }}
          commitId: ${{ steps.version.outputs.GitCommitId }}
          destinationDirectory: site
          sourceDirectory: docs
          semanticVersion: ${{ steps.version.outputs.SemVer2 }}
          version: ${{ steps.version.outputs.Version }}
      - name: Send message
        uses: gavanlamb/github-actions/.github/actions/slack/built@main
        if: always()
        with:
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          version: ${{ steps.version.outputs.Version }}
          status: ${{ job.status }}
          includeIntegrationTests: 'false'
          includeUnitTests: 'false'

  Preview:
    name: Preview
    runs-on: ubuntu-latest
    needs: build
    env:
      sitePath: ${{ github.repository }}/release/preview${{ github.event.pull_request.number }}/site
    environment: 
      url: https://gavanlamb-github-actions-assets.s3.ap-southeast-2.amazonaws.com/${{ env.sitePath }}/index.html
      name: Preview${{ github.event.pull_request.number }}
    steps:
      - name: Deploy ${{ env.artifactName }}
        uses: gavanlamb/github-actions/.github/actions/hugo/deploy-to-s3@main
        with:
          artifactName: ${{ env.artifactName }}
          artifactDirectory: site
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsS3Bucket: ${{ vars.AWS_S3_CICD_BUCKET }}
          awsS3Path: ${{ env.sitePath }}
          awsS3Region: ${{ vars.AWS_DEFAULT_REGION }}
      - name: Send message
        uses: gavanlamb/github-actions/.github/actions/slack/released@main
        if: always()
        with:
          environment: Preview${{ github.event.pull_request.number }}
          includeSystemTests: 'false'
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          version: ${{ needs.build.outputs.version }}
