name: 'Release: create'

on:
  workflow_dispatch:

concurrency:
  cancel-in-progress: false
  group: create-release-${{ github.ref_name }}

permissions:
  contents: read
  pull-requests: write

jobs:
  create_release_branch:
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: gavanlamb/github-actions/.github/actions/version/create-release@main
        name: Create release
        id: create-release
      - name: Open PR to merge main to ${{ steps.create-release.outputs.new-branch }}
        id: prepare-release
        shell: bash
        run: |
          gh pr create \
            --base ${{ steps.create-release.outputs.new-branch }} \
            --head main \
            --title "Merge main to ${{ steps.create-release.outputs.new-branch }}" \
            --body "Merge main to ${{ steps.create-release.outputs.new-branch }}"
        env:
          GH_TOKEN: ${{ github.token }}