name: 'Release: create PRs'

run-name: ${{ github.ref_name }}

on:
  workflow_dispatch:

env:
  artifactName: Website

concurrency:
  cancel-in-progress: false
  group: close-release-${{ github.ref_name }}

permissions:
  contents: read
  pull-requests: write

jobs:
  Create:
    name: Create PRs
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.Version }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Open PR to merge ${{ github.ref_name }} to develop
        id: open-pr-to-develop
        shell: bash
        run: |
          gh pr create \
            --base develop \
            --head ${{ github.ref_name }} \
            --title "Merge ${{ github.ref_name }} to develop" \
            --body "Merge ${{ github.ref_name }} to develop"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Open PR to merge ${{ github.ref_name }} to main
        id: open-pr-to-main
        shell: bash
        run: |
          gh pr create \
            --base main \
            --head ${{ github.ref_name }} \
            --title "Merge ${{ github.ref_name }} to main" \
            --body "Merge ${{ github.ref_name }} to main"
        env:
          GH_TOKEN: ${{ github.token }}
