name: 'Release: create'

on:
  workflow_dispatch:

concurrency:
  cancel-in-progress: false
  group: create-release-${{ github.ref_name }}

permissions:
  contents: write
  pull-requests: write

jobs:
  create_release_branch:
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: gavanlamb/github-actions/.github/actions/release/create-release-branch@main
        name: Create release branch
        id: create-release-branch
      - uses: gavanlamb/github-actions/.github/actions/pull-request/create@main
        name: Open PR to merge main to ${{ steps.create-release-branch.outputs.release-branch-name }}
        with:
            base-branch-name: ${{ steps.create-release-branch.outputs.release-branch-name }}
            head-branch-name: main
