name: 'Release: create'

on:
  workflow_dispatch:

concurrency:
  cancel-in-progress: false
  group: create-release-${{ github.ref_name }}

permissions:
  contents: read
  pull-requests: write

jobs:
  create_release_branch:
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: gavanlamb/github-actions/.github/actions/release/create-release-branch@main
        name: Create release branch
        id: create-release-branch
      - name: Open PR to merge main to ${{ steps.create-release-branch.outputs.release-branch-name }}
        shell: bash
        run: |
          gh pr create \
            --base ${{ steps.create-release-branch.outputs.release-branch-name }} \
            --head main \
            --title "Merge main to ${{ steps.create-release-branch.outputs.release-branch-name }}" \
            --body "Merge main to ${{ steps.create-release-branch.outputs.release-branch-name }}"
        env:
          GH_TOKEN: ${{ github.token }}