name: Create release

on:
  workflow_dispatch:

concurrency:
  cancel-in-progress: false
  group: create-release-${{ github.ref_name }}

jobs:
  create_release_branch:
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: gavanlamb/github-actions/.github/actions/version/create-release@main
        name: Create release
        id: create-release
      - name: Open PR to merge main to release
        uses: peter-evans/create-pull-request@v6
        with:
          base: ${{ steps.create-release.outputs.new-branch }}
          branch: main