name: 'Remove environment'

on:
  pull_request:
    types:
      - closed

concurrency:
  cancel-in-progress: false
  group: remove-environment-${{ github.ref_name }}
  
env:
  environment: Preview${{ github.event.pull_request.number }}
  site-path: ${{ github.repository }}/release/preview${{ github.event.pull_request.number }}

jobs:
  clean-up:
    name: Clean up
    runs-on: ubuntu-latest
    steps:
      - name: Remove assets from S3
        uses: vitorsgomes/s3-rm-action@master
        with:
          args: --recursive
        env:
          AWS_S3_BUCKET: ${{ vars.AWS_S3_CICD_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          PATH_TO_DELETE: ${{ env.site-path }}
      - name: Delete ${{ env.environment }} environment
        uses: strumwolf/delete-deployment-environment@v3.0.0
        with:
          token: ${{ secrets.PAT_GITHUB_ACTIONS }}
          environment: ${{ env.environment }}
