name: Pull request raised

run-name: PR#${{ github.event.pull_request.number }}

on:
  pull_request:
    types:
      - opened

concurrency:
  cancel-in-progress: false
  group: update-pull-request-description-${{ github.head_ref }}

jobs:
  update-pr-description:
    name: Update PR description
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/checkout@v2
        name: Checkout
      - name: Get PR#${{ github.event.pull_request.number }} description
        id: get_pr_description
        shell: bash
        run: |
          PR_DESCRIPTION_TEMPLATE=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq '.body')
          echo "pr-description-template<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_DESCRIPTION_TEMPLATE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Replace PR#${{ github.event.pull_request.number }} description variables
        id: update_pr_description
        shell: bash
        run: |
          TICKET_NUMBER="XXXX-XXXX"
          TICKET_TITLE="Sample title"
          REPOSITORY_NAME="${{ github.repository }}"
          BRANCH_NAME="${{ github.head_ref }}"
          PR_DESCRIPTION="${{ steps.get_pr_description.outputs.pr-description-template }}"
          
          PR_DESCRIPTION=$(sed -e "s|{{TICKET_NUMBER}}|$TICKET_NUMBER|g" \
          -e "s|{{TICKET_TITLE}}|$TICKET_TITLE|g" \
          -e "s|{{REPOSITORY_NAME}}|$REPOSITORY_NAME|g" \
          -e "s|{{BRANCH_NAME}}|$BRANCH_NAME|g" <<< $PR_DESCRIPTION)
          
          echo "pr-description<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_DESCRIPTION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Update PR#${{ github.event.pull_request.number }} description
        shell: bash
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --body "${{ steps.update_pr_description.outputs.pr-description }}"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Send message
        uses: gavanlamb/github-actions/.github/actions/slack/pull-request-created@main
        if: always()
        with:
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
