name: Pull request raised

run-name: PR#${{ github.event.pull_request.number }}

on:
  pull_request:
    types:
      - opened
    branches-ignore:
      - release/**

concurrency:
  cancel-in-progress: false
  group: update-pull-request-description-${{ github.head_ref }}

env: 
  JIRA_URL: 'https://originenergy.atlassian.net/'

jobs:
  update-pr-description:
    name: Update PR description
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/checkout@v2
        name: Checkout
      - name: Get issue details
        uses: gavanlamb/github-actions/.github/actions/jira/get-issue-details@main
        id: get-issue-details
        with:
          jiraBaseUrl: ${{ env.JIRA_URL }}
          jiraUserEmail: gavan.lamb@origin.com.au
          jiraApiToken: ${{ secrets.JIRA_API_TOKEN }}
      - name: Update PR
        uses: gavanlamb/github-actions/.github/actions/pull-request/update-pr@main
        id: update-pr
        with:
          ticketIdentifier: ${{ steps.get-issue-details.outputs.issueIdentifier }}
          ticketTitle: ${{ steps.get-issue-details.outputs.issueName }}
          ticketUrl: ${{ env.JIRA_URL }}/browse/${{ steps.get-issue-details.outputs.issueIdentifier }}
      - name: Send message
        uses: gavanlamb/github-actions/.github/actions/slack/pull-request-created@main
        if: always()
        with:
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          title: ${{ steps.update-pr.outputs.title }}
