name: Update pull request description

on:
  pull_request:
    types:
      - opened



jobs:
  replace-description:
    name: Replace description
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout ${{ github.ref }} 
        with:
          ref: ${{ github.ref }}
      - name: Replace repository name
        uses: kaskar2008/action-pr-description-replace@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          find: '{{GITHUB_REPOSITORY}}'
          replace: ${{ github.head_ref }}
      - name: Replace ref name
        uses: kaskar2008/action-pr-description-replace@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          find: '{{GITHUB_REF}}'
          replace: ${{ github.ref }}
      - name: Replace ticket number
        uses: kaskar2008/action-pr-description-replace@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          find: '{{TICKET_NUMBER}}'
          replace: '#10'
      - name: Replace ticket title
        uses: kaskar2008/action-pr-description-replace@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          find: '{{TICKET_TITLE}}'
          replace: 'Ticket title'