name: Pull request raised

run-name: PR#${{ github.event.pull_request.number }}

on:
  pull_request:
    types:
      - opened

concurrency:
  cancel-in-progress: false
  group: update-pull-request-description-${{ github.head_ref }}

jobs:
  update-pr-description:
    name: Update PR description
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/checkout@v2
        name: Checkout
      - name: Get issue details
        uses: gavanlamb/github-actions/.github/actions/jira/get-issue-details@main
        id: get-issue-details
      - name: Update PR
        uses: gavanlamb/github-actions/.github/actions/jira/get-issue-details@main
        id: update-pr
        with:
          ticketIdentifier: ${{ steps.get-issue-details.outputs.issueIdentifier }}
          ticketTitle: ${{ steps.get-issue-details.outputs.issueName }}
          ticketUrl: https://jira.com/${{ steps.get-issue-details.outputs.issueIdentifier }}
      - name: Send message
        uses: gavanlamb/github-actions/.github/actions/slack/pull-request-created@main
        if: always()
        with:
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          title: ${{ steps.update-pr.outputs.title }}
