name: Update pull request description

on:
  pull_request:
    types:
      - opened

jobs:
  replace-repository-name:
    name: Replace repository name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout ${{ github.ref }}
        with:
          ref: ${{ github.ref }}
      - name: Replace {{GITHUB_REPOSITORY}} with ${{ github.head_ref }}
        uses: kaskar2008/action-pr-description-replace@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          find: '{{GITHUB_REPOSITORY}}'
          replace: ${{ github.head_ref }}
      - name: Replace {{GITHUB_REF}} with ${{ github.ref }}
        uses: kaskar2008/action-pr-description-replace@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          find: '{{GITHUB_REF}}'
          replace: ${{ github.ref }}
      - name: Replace {{TICKET_NUMBER}} with #10
        uses: kaskar2008/action-pr-description-replace@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          find: '{{TICKET_NUMBER}}'
          replace: '#10'
      - name: Replace {{TICKET_TITLE}} with Ticket title
        uses: kaskar2008/action-pr-description-replace@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          find: '{{TICKET_TITLE}}'
          replace: 'Ticket title'